### ISSUE TITLE
dim&ods

### ISSUE THREAD

**Issue by ketingli1** [ketingli1/ketingli1.github.io#3]

**Comment by ketingli1** [comment]
[odsdata.zip](https://github.com/ketingli1/ketingli1.github.io/files/3533212/odsdata.zip)
[dimData.zip](https://github.com/ketingli1/ketingli1.github.io/files/3533213/dimData.zip)

**Comment by ketingli1** [comment]
[data.zip](https://github.com/ketingli1/ketingli1.github.io/files/3533491/data.zip)

**Comment by ketingli1** [comment]
org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainIntegerDictionary

**Comment by ketingli1** [comment]
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 5.0 failed 4 times, most recent failure: Lost task 9.3 in stage 5.0 (TID 348, tbdp-hbs2, executor 4): java.lang.UnsupportedOperationException: org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainIntegerDictionary
	at org.apache.parquet.column.Dictionary.decodeToBinary(Dictionary.java:44)
	at org.apache.spark.sql.execution.vectorized.ColumnVector.getUTF8String(ColumnVector.java:645)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:148)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
